//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 04:06:25 PM BST 
//


package com.sven.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}image-link" minOccurs="0"/&gt;
 *         &lt;element ref="{}caption" minOccurs="0"/&gt;
 *         &lt;element ref="{}source" minOccurs="0"/&gt;
 *         &lt;element ref="{}poc-citation" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="fig-id" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *       &lt;attribute name="ref-id" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *       &lt;attribute name="figs-fig-id" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imageLink",
    "caption",
    "source",
    "pocCitation"
})
@XmlRootElement(name = "figure")
public class Figure {

    @XmlElement(name = "image-link")
    protected ImageLink imageLink;
    protected String caption;
    protected String source;
    @XmlElement(name = "poc-citation")
    protected PocCitation pocCitation;
    @XmlAttribute(name = "fig-id")
    protected Byte figId;
    @XmlAttribute(name = "ref-id")
    protected Byte refId;
    @XmlAttribute(name = "figs-fig-id")
    protected Byte figsFigId;

    /**
     * Gets the value of the imageLink property.
     * 
     * @return
     *     possible object is
     *     {@link ImageLink }
     *     
     */
    public ImageLink getImageLink() {
        return imageLink;
    }

    /**
     * Sets the value of the imageLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageLink }
     *     
     */
    public void setImageLink(ImageLink value) {
        this.imageLink = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the pocCitation property.
     * 
     * @return
     *     possible object is
     *     {@link PocCitation }
     *     
     */
    public PocCitation getPocCitation() {
        return pocCitation;
    }

    /**
     * Sets the value of the pocCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PocCitation }
     *     
     */
    public void setPocCitation(PocCitation value) {
        this.pocCitation = value;
    }

    /**
     * Gets the value of the figId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getFigId() {
        return figId;
    }

    /**
     * Sets the value of the figId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFigId(Byte value) {
        this.figId = value;
    }

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setRefId(Byte value) {
        this.refId = value;
    }

    /**
     * Gets the value of the figsFigId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getFigsFigId() {
        return figsFigId;
    }

    /**
     * Sets the value of the figsFigId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFigsFigId(Byte value) {
        this.figsFigId = value;
    }

}
