//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 04:06:25 PM BST 
//


package com.sven.xml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sven.xml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TopicTitle_QNAME = new QName("", "topic-title");
    private final static QName _Citation_QNAME = new QName("", "citation");
    private final static QName _FulltextUrl_QNAME = new QName("", "fulltext-url");
    private final static QName _Url_QNAME = new QName("", "url");
    private final static QName _LastUpdated_QNAME = new QName("", "last-updated");
    private final static QName _RelatedTopics_QNAME = new QName("", "related-topics");
    private final static QName _Highlight_QNAME = new QName("", "highlight");
    private final static QName _Caption_QNAME = new QName("", "caption");
    private final static QName _Source_QNAME = new QName("", "source");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _SectionHeader_QNAME = new QName("", "section-header");
    private final static QName _FactorName_QNAME = new QName("", "factor-name");
    private final static QName _Result_QNAME = new QName("", "result");
    private final static QName _PtGroup_QNAME = new QName("", "pt-group");
    private final static QName _TxType_QNAME = new QName("", "tx-type");
    private final static QName _Details_QNAME = new QName("", "details");
    private final static QName _LastPublished_QNAME = new QName("", "last-published");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sven.xml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Reason }
     * 
     */
    public Reason createReason() {
        return new Reason();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link Synonym }
     * 
     */
    public Synonym createSynonym() {
        return new Synonym();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link PocCitation }
     * 
     */
    public PocCitation createPocCitation() {
        return new PocCitation();
    }

    /**
     * Create an instance of {@link VersionHistory }
     * 
     */
    public VersionHistory createVersionHistory() {
        return new VersionHistory();
    }

    /**
     * Create an instance of {@link Synonyms }
     * 
     */
    public Synonyms createSynonyms() {
        return new Synonyms();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Para }
     * 
     */
    public Para createPara() {
        return new Para();
    }

    /**
     * Create an instance of {@link Figure }
     * 
     */
    public Figure createFigure() {
        return new Figure();
    }

    /**
     * Create an instance of {@link ImageLink }
     * 
     */
    public ImageLink createImageLink() {
        return new ImageLink();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link Detail }
     * 
     */
    public Detail createDetail() {
        return new Detail();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Vignette }
     * 
     */
    public Vignette createVignette() {
        return new Vignette();
    }

    /**
     * Create an instance of {@link RiskFactor }
     * 
     */
    public RiskFactor createRiskFactor() {
        return new RiskFactor();
    }

    /**
     * Create an instance of {@link Definition }
     * 
     */
    public Definition createDefinition() {
        return new Definition();
    }

    /**
     * Create an instance of {@link Classifications }
     * 
     */
    public Classifications createClassifications() {
        return new Classifications();
    }

    /**
     * Create an instance of {@link Vignettes }
     * 
     */
    public Vignettes createVignettes() {
        return new Vignettes();
    }

    /**
     * Create an instance of {@link OtherPresentations }
     * 
     */
    public OtherPresentations createOtherPresentations() {
        return new OtherPresentations();
    }

    /**
     * Create an instance of {@link Epidemiology }
     * 
     */
    public Epidemiology createEpidemiology() {
        return new Epidemiology();
    }

    /**
     * Create an instance of {@link Etiology }
     * 
     */
    public Etiology createEtiology() {
        return new Etiology();
    }

    /**
     * Create an instance of {@link Pathophysiology }
     * 
     */
    public Pathophysiology createPathophysiology() {
        return new Pathophysiology();
    }

    /**
     * Create an instance of {@link RiskFactors }
     * 
     */
    public RiskFactors createRiskFactors() {
        return new RiskFactors();
    }

    /**
     * Create an instance of {@link SectionText }
     * 
     */
    public SectionText createSectionText() {
        return new SectionText();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Approach }
     * 
     */
    public Approach createApproach() {
        return new Approach();
    }

    /**
     * Create an instance of {@link DiagnosticFactors }
     * 
     */
    public DiagnosticFactors createDiagnosticFactors() {
        return new DiagnosticFactors();
    }

    /**
     * Create an instance of {@link Factor }
     * 
     */
    public Factor createFactor() {
        return new Factor();
    }

    /**
     * Create an instance of {@link Tests }
     * 
     */
    public Tests createTests() {
        return new Tests();
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link Differentials }
     * 
     */
    public Differentials createDifferentials() {
        return new Differentials();
    }

    /**
     * Create an instance of {@link Differential }
     * 
     */
    public Differential createDifferential() {
        return new Differential();
    }

    /**
     * Create an instance of {@link SignSymptoms }
     * 
     */
    public SignSymptoms createSignSymptoms() {
        return new SignSymptoms();
    }

    /**
     * Create an instance of {@link DiagnosticCriteria }
     * 
     */
    public DiagnosticCriteria createDiagnosticCriteria() {
        return new DiagnosticCriteria();
    }

    /**
     * Create an instance of {@link Criteria }
     * 
     */
    public Criteria createCriteria() {
        return new Criteria();
    }

    /**
     * Create an instance of {@link TxOptions }
     * 
     */
    public TxOptions createTxOptions() {
        return new TxOptions();
    }

    /**
     * Create an instance of {@link TxOption }
     * 
     */
    public TxOption createTxOption() {
        return new TxOption();
    }

    /**
     * Create an instance of {@link Comments }
     * 
     */
    public Comments createComments() {
        return new Comments();
    }

    /**
     * Create an instance of {@link Regimens }
     * 
     */
    public Regimens createRegimens() {
        return new Regimens();
    }

    /**
     * Create an instance of {@link Regimen }
     * 
     */
    public Regimen createRegimen() {
        return new Regimen();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link EmergingTxs }
     * 
     */
    public EmergingTxs createEmergingTxs() {
        return new EmergingTxs();
    }

    /**
     * Create an instance of {@link EmergingTx }
     * 
     */
    public EmergingTx createEmergingTx() {
        return new EmergingTx();
    }

    /**
     * Create an instance of {@link Guidelines }
     * 
     */
    public Guidelines createGuidelines() {
        return new Guidelines();
    }

    /**
     * Create an instance of {@link Guideline }
     * 
     */
    public Guideline createGuideline() {
        return new Guideline();
    }

    /**
     * Create an instance of {@link Summary }
     * 
     */
    public Summary createSummary() {
        return new Summary();
    }

    /**
     * Create an instance of {@link Outlook }
     * 
     */
    public Outlook createOutlook() {
        return new Outlook();
    }

    /**
     * Create an instance of {@link Complications }
     * 
     */
    public Complications createComplications() {
        return new Complications();
    }

    /**
     * Create an instance of {@link Complication }
     * 
     */
    public Complication createComplication() {
        return new Complication();
    }

    /**
     * Create an instance of {@link Recommendations }
     * 
     */
    public Recommendations createRecommendations() {
        return new Recommendations();
    }

    /**
     * Create an instance of {@link Monitoring }
     * 
     */
    public Monitoring createMonitoring() {
        return new Monitoring();
    }

    /**
     * Create an instance of {@link PatientInstructions }
     * 
     */
    public PatientInstructions createPatientInstructions() {
        return new PatientInstructions();
    }

    /**
     * Create an instance of {@link PreventiveActions }
     * 
     */
    public PreventiveActions createPreventiveActions() {
        return new PreventiveActions();
    }

    /**
     * Create an instance of {@link Figures }
     * 
     */
    public Figures createFigures() {
        return new Figures();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "topic-title")
    public JAXBElement<String> createTopicTitle(String value) {
        return new JAXBElement<String>(_TopicTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "citation")
    public JAXBElement<String> createCitation(String value) {
        return new JAXBElement<String>(_Citation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fulltext-url")
    public JAXBElement<String> createFulltextUrl(String value) {
        return new JAXBElement<String>(_FulltextUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "last-updated")
    public JAXBElement<XMLGregorianCalendar> createLastUpdated(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastUpdated_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "related-topics")
    public JAXBElement<String> createRelatedTopics(String value) {
        return new JAXBElement<String>(_RelatedTopics_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "highlight")
    public JAXBElement<String> createHighlight(String value) {
        return new JAXBElement<String>(_Highlight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "caption")
    public JAXBElement<String> createCaption(String value) {
        return new JAXBElement<String>(_Caption_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source")
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section-header")
    public JAXBElement<String> createSectionHeader(String value) {
        return new JAXBElement<String>(_SectionHeader_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "factor-name")
    public JAXBElement<String> createFactorName(String value) {
        return new JAXBElement<String>(_FactorName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "result")
    public JAXBElement<String> createResult(String value) {
        return new JAXBElement<String>(_Result_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pt-group")
    public JAXBElement<String> createPtGroup(String value) {
        return new JAXBElement<String>(_PtGroup_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tx-type")
    public JAXBElement<String> createTxType(String value) {
        return new JAXBElement<String>(_TxType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "details")
    public JAXBElement<String> createDetails(String value) {
        return new JAXBElement<String>(_Details_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "last-published")
    public JAXBElement<Short> createLastPublished(Short value) {
        return new JAXBElement<Short>(_LastPublished_QNAME, Short.class, null, value);
    }

}
