//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 04:06:25 PM BST 
//


package com.sven.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}monitoring"/&gt;
 *         &lt;element ref="{}patient-instructions"/&gt;
 *         &lt;element ref="{}preventive-actions"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "monitoring",
    "patientInstructions",
    "preventiveActions"
})
@XmlRootElement(name = "recommendations")
public class Recommendations {

    @XmlElement(required = true)
    protected Monitoring monitoring;
    @XmlElement(name = "patient-instructions", required = true)
    protected PatientInstructions patientInstructions;
    @XmlElement(name = "preventive-actions", required = true)
    protected PreventiveActions preventiveActions;

    /**
     * Gets the value of the monitoring property.
     * 
     * @return
     *     possible object is
     *     {@link Monitoring }
     *     
     */
    public Monitoring getMonitoring() {
        return monitoring;
    }

    /**
     * Sets the value of the monitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link Monitoring }
     *     
     */
    public void setMonitoring(Monitoring value) {
        this.monitoring = value;
    }

    /**
     * Gets the value of the patientInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link PatientInstructions }
     *     
     */
    public PatientInstructions getPatientInstructions() {
        return patientInstructions;
    }

    /**
     * Sets the value of the patientInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientInstructions }
     *     
     */
    public void setPatientInstructions(PatientInstructions value) {
        this.patientInstructions = value;
    }

    /**
     * Gets the value of the preventiveActions property.
     * 
     * @return
     *     possible object is
     *     {@link PreventiveActions }
     *     
     */
    public PreventiveActions getPreventiveActions() {
        return preventiveActions;
    }

    /**
     * Sets the value of the preventiveActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreventiveActions }
     *     
     */
    public void setPreventiveActions(PreventiveActions value) {
        this.preventiveActions = value;
    }

}
