//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 04:06:25 PM BST 
//


package com.sven.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}poc-citation"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ref-id" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *       &lt;attribute name="refs-ref-id" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pocCitation"
})
@XmlRootElement(name = "reference")
public class Reference {

    @XmlElement(name = "poc-citation", required = true)
    protected PocCitation pocCitation;
    @XmlAttribute(name = "ref-id")
    protected Byte refId;
    @XmlAttribute(name = "refs-ref-id")
    protected Byte refsRefId;

    /**
     * Gets the value of the pocCitation property.
     * 
     * @return
     *     possible object is
     *     {@link PocCitation }
     *     
     */
    public PocCitation getPocCitation() {
        return pocCitation;
    }

    /**
     * Sets the value of the pocCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PocCitation }
     *     
     */
    public void setPocCitation(PocCitation value) {
        this.pocCitation = value;
    }

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setRefId(Byte value) {
        this.refId = value;
    }

    /**
     * Gets the value of the refsRefId property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getRefsRefId() {
        return refsRefId;
    }

    /**
     * Sets the value of the refsRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setRefsRefId(Byte value) {
        this.refsRefId = value;
    }

}
