//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 04:06:25 PM BST 
//


package com.sven.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}section-header" minOccurs="0"/&gt;
 *         &lt;element ref="{}section-text" minOccurs="0"/&gt;
 *         &lt;element ref="{}definition" minOccurs="0"/&gt;
 *         &lt;element ref="{}classifications" minOccurs="0"/&gt;
 *         &lt;element ref="{}vignettes" minOccurs="0"/&gt;
 *         &lt;element ref="{}other-presentations" minOccurs="0"/&gt;
 *         &lt;element ref="{}epidemiology" minOccurs="0"/&gt;
 *         &lt;element ref="{}etiology" minOccurs="0"/&gt;
 *         &lt;element ref="{}pathophysiology" minOccurs="0"/&gt;
 *         &lt;element ref="{}risk-factors" minOccurs="0"/&gt;
 *         &lt;element ref="{}approach" minOccurs="0"/&gt;
 *         &lt;element ref="{}diagnostic-factors" minOccurs="0"/&gt;
 *         &lt;element ref="{}tests" minOccurs="0"/&gt;
 *         &lt;element ref="{}differentials" minOccurs="0"/&gt;
 *         &lt;element ref="{}diagnostic-criteria" minOccurs="0"/&gt;
 *         &lt;element ref="{}tx-options" minOccurs="0"/&gt;
 *         &lt;element ref="{}emerging-txs" minOccurs="0"/&gt;
 *         &lt;element ref="{}guidelines" minOccurs="0"/&gt;
 *         &lt;element ref="{}outlook" minOccurs="0"/&gt;
 *         &lt;element ref="{}complications" minOccurs="0"/&gt;
 *         &lt;element ref="{}recommendations" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sectionHeader",
    "sectionText",
    "definition",
    "classifications",
    "vignettes",
    "otherPresentations",
    "epidemiology",
    "etiology",
    "pathophysiology",
    "riskFactors",
    "approach",
    "diagnosticFactors",
    "tests",
    "differentials",
    "diagnosticCriteria",
    "txOptions",
    "emergingTxs",
    "guidelines",
    "outlook",
    "complications",
    "recommendations"
})
@XmlRootElement(name = "section")
public class Section {

    @XmlElement(name = "section-header")
    protected String sectionHeader;
    @XmlElement(name = "section-text")
    protected SectionText sectionText;
    protected Definition definition;
    protected Classifications classifications;
    protected Vignettes vignettes;
    @XmlElement(name = "other-presentations")
    protected OtherPresentations otherPresentations;
    protected Epidemiology epidemiology;
    protected Etiology etiology;
    protected Pathophysiology pathophysiology;
    @XmlElement(name = "risk-factors")
    protected RiskFactors riskFactors;
    protected Approach approach;
    @XmlElement(name = "diagnostic-factors")
    protected DiagnosticFactors diagnosticFactors;
    protected Tests tests;
    protected Differentials differentials;
    @XmlElement(name = "diagnostic-criteria")
    protected DiagnosticCriteria diagnosticCriteria;
    @XmlElement(name = "tx-options")
    protected TxOptions txOptions;
    @XmlElement(name = "emerging-txs")
    protected EmergingTxs emergingTxs;
    protected Guidelines guidelines;
    protected Outlook outlook;
    protected Complications complications;
    protected Recommendations recommendations;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the sectionHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSectionHeader() {
        return sectionHeader;
    }

    /**
     * Sets the value of the sectionHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSectionHeader(String value) {
        this.sectionHeader = value;
    }

    /**
     * Gets the value of the sectionText property.
     * 
     * @return
     *     possible object is
     *     {@link SectionText }
     *     
     */
    public SectionText getSectionText() {
        return sectionText;
    }

    /**
     * Sets the value of the sectionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link SectionText }
     *     
     */
    public void setSectionText(SectionText value) {
        this.sectionText = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link Definition }
     *     
     */
    public Definition getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definition }
     *     
     */
    public void setDefinition(Definition value) {
        this.definition = value;
    }

    /**
     * Gets the value of the classifications property.
     * 
     * @return
     *     possible object is
     *     {@link Classifications }
     *     
     */
    public Classifications getClassifications() {
        return classifications;
    }

    /**
     * Sets the value of the classifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classifications }
     *     
     */
    public void setClassifications(Classifications value) {
        this.classifications = value;
    }

    /**
     * Gets the value of the vignettes property.
     * 
     * @return
     *     possible object is
     *     {@link Vignettes }
     *     
     */
    public Vignettes getVignettes() {
        return vignettes;
    }

    /**
     * Sets the value of the vignettes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vignettes }
     *     
     */
    public void setVignettes(Vignettes value) {
        this.vignettes = value;
    }

    /**
     * Gets the value of the otherPresentations property.
     * 
     * @return
     *     possible object is
     *     {@link OtherPresentations }
     *     
     */
    public OtherPresentations getOtherPresentations() {
        return otherPresentations;
    }

    /**
     * Sets the value of the otherPresentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherPresentations }
     *     
     */
    public void setOtherPresentations(OtherPresentations value) {
        this.otherPresentations = value;
    }

    /**
     * Gets the value of the epidemiology property.
     * 
     * @return
     *     possible object is
     *     {@link Epidemiology }
     *     
     */
    public Epidemiology getEpidemiology() {
        return epidemiology;
    }

    /**
     * Sets the value of the epidemiology property.
     * 
     * @param value
     *     allowed object is
     *     {@link Epidemiology }
     *     
     */
    public void setEpidemiology(Epidemiology value) {
        this.epidemiology = value;
    }

    /**
     * Gets the value of the etiology property.
     * 
     * @return
     *     possible object is
     *     {@link Etiology }
     *     
     */
    public Etiology getEtiology() {
        return etiology;
    }

    /**
     * Sets the value of the etiology property.
     * 
     * @param value
     *     allowed object is
     *     {@link Etiology }
     *     
     */
    public void setEtiology(Etiology value) {
        this.etiology = value;
    }

    /**
     * Gets the value of the pathophysiology property.
     * 
     * @return
     *     possible object is
     *     {@link Pathophysiology }
     *     
     */
    public Pathophysiology getPathophysiology() {
        return pathophysiology;
    }

    /**
     * Sets the value of the pathophysiology property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pathophysiology }
     *     
     */
    public void setPathophysiology(Pathophysiology value) {
        this.pathophysiology = value;
    }

    /**
     * Gets the value of the riskFactors property.
     * 
     * @return
     *     possible object is
     *     {@link RiskFactors }
     *     
     */
    public RiskFactors getRiskFactors() {
        return riskFactors;
    }

    /**
     * Sets the value of the riskFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskFactors }
     *     
     */
    public void setRiskFactors(RiskFactors value) {
        this.riskFactors = value;
    }

    /**
     * Gets the value of the approach property.
     * 
     * @return
     *     possible object is
     *     {@link Approach }
     *     
     */
    public Approach getApproach() {
        return approach;
    }

    /**
     * Sets the value of the approach property.
     * 
     * @param value
     *     allowed object is
     *     {@link Approach }
     *     
     */
    public void setApproach(Approach value) {
        this.approach = value;
    }

    /**
     * Gets the value of the diagnosticFactors property.
     * 
     * @return
     *     possible object is
     *     {@link DiagnosticFactors }
     *     
     */
    public DiagnosticFactors getDiagnosticFactors() {
        return diagnosticFactors;
    }

    /**
     * Sets the value of the diagnosticFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagnosticFactors }
     *     
     */
    public void setDiagnosticFactors(DiagnosticFactors value) {
        this.diagnosticFactors = value;
    }

    /**
     * Gets the value of the tests property.
     * 
     * @return
     *     possible object is
     *     {@link Tests }
     *     
     */
    public Tests getTests() {
        return tests;
    }

    /**
     * Sets the value of the tests property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tests }
     *     
     */
    public void setTests(Tests value) {
        this.tests = value;
    }

    /**
     * Gets the value of the differentials property.
     * 
     * @return
     *     possible object is
     *     {@link Differentials }
     *     
     */
    public Differentials getDifferentials() {
        return differentials;
    }

    /**
     * Sets the value of the differentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link Differentials }
     *     
     */
    public void setDifferentials(Differentials value) {
        this.differentials = value;
    }

    /**
     * Gets the value of the diagnosticCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link DiagnosticCriteria }
     *     
     */
    public DiagnosticCriteria getDiagnosticCriteria() {
        return diagnosticCriteria;
    }

    /**
     * Sets the value of the diagnosticCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagnosticCriteria }
     *     
     */
    public void setDiagnosticCriteria(DiagnosticCriteria value) {
        this.diagnosticCriteria = value;
    }

    /**
     * Gets the value of the txOptions property.
     * 
     * @return
     *     possible object is
     *     {@link TxOptions }
     *     
     */
    public TxOptions getTxOptions() {
        return txOptions;
    }

    /**
     * Sets the value of the txOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxOptions }
     *     
     */
    public void setTxOptions(TxOptions value) {
        this.txOptions = value;
    }

    /**
     * Gets the value of the emergingTxs property.
     * 
     * @return
     *     possible object is
     *     {@link EmergingTxs }
     *     
     */
    public EmergingTxs getEmergingTxs() {
        return emergingTxs;
    }

    /**
     * Sets the value of the emergingTxs property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmergingTxs }
     *     
     */
    public void setEmergingTxs(EmergingTxs value) {
        this.emergingTxs = value;
    }

    /**
     * Gets the value of the guidelines property.
     * 
     * @return
     *     possible object is
     *     {@link Guidelines }
     *     
     */
    public Guidelines getGuidelines() {
        return guidelines;
    }

    /**
     * Sets the value of the guidelines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Guidelines }
     *     
     */
    public void setGuidelines(Guidelines value) {
        this.guidelines = value;
    }

    /**
     * Gets the value of the outlook property.
     * 
     * @return
     *     possible object is
     *     {@link Outlook }
     *     
     */
    public Outlook getOutlook() {
        return outlook;
    }

    /**
     * Sets the value of the outlook property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outlook }
     *     
     */
    public void setOutlook(Outlook value) {
        this.outlook = value;
    }

    /**
     * Gets the value of the complications property.
     * 
     * @return
     *     possible object is
     *     {@link Complications }
     *     
     */
    public Complications getComplications() {
        return complications;
    }

    /**
     * Sets the value of the complications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Complications }
     *     
     */
    public void setComplications(Complications value) {
        this.complications = value;
    }

    /**
     * Gets the value of the recommendations property.
     * 
     * @return
     *     possible object is
     *     {@link Recommendations }
     *     
     */
    public Recommendations getRecommendations() {
        return recommendations;
    }

    /**
     * Sets the value of the recommendations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recommendations }
     *     
     */
    public void setRecommendations(Recommendations value) {
        this.recommendations = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
