//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.13 at 04:06:25 PM BST 
//


package com.sven.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}pt-group"/&gt;
 *         &lt;element ref="{}tx-type"/&gt;
 *         &lt;element ref="{}comments"/&gt;
 *         &lt;element ref="{}regimens" minOccurs="0"/&gt;
 *         &lt;element ref="{}tx-options"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="timeframe" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="tx-line" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ptGroup",
    "txType",
    "comments",
    "regimens",
    "txOptions"
})
@XmlRootElement(name = "tx-option")
public class TxOption {

    @XmlElement(name = "pt-group", required = true)
    protected String ptGroup;
    @XmlElement(name = "tx-type", required = true)
    protected String txType;
    @XmlElement(required = true)
    protected Comments comments;
    protected Regimens regimens;
    @XmlElement(name = "tx-options", required = true)
    protected TxOptions txOptions;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "timeframe")
    protected String timeframe;
    @XmlAttribute(name = "tx-line")
    protected String txLine;

    /**
     * Gets the value of the ptGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtGroup() {
        return ptGroup;
    }

    /**
     * Sets the value of the ptGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtGroup(String value) {
        this.ptGroup = value;
    }

    /**
     * Gets the value of the txType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxType() {
        return txType;
    }

    /**
     * Sets the value of the txType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxType(String value) {
        this.txType = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link Comments }
     *     
     */
    public Comments getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comments }
     *     
     */
    public void setComments(Comments value) {
        this.comments = value;
    }

    /**
     * Gets the value of the regimens property.
     * 
     * @return
     *     possible object is
     *     {@link Regimens }
     *     
     */
    public Regimens getRegimens() {
        return regimens;
    }

    /**
     * Sets the value of the regimens property.
     * 
     * @param value
     *     allowed object is
     *     {@link Regimens }
     *     
     */
    public void setRegimens(Regimens value) {
        this.regimens = value;
    }

    /**
     * Gets the value of the txOptions property.
     * 
     * @return
     *     possible object is
     *     {@link TxOptions }
     *     
     */
    public TxOptions getTxOptions() {
        return txOptions;
    }

    /**
     * Sets the value of the txOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxOptions }
     *     
     */
    public void setTxOptions(TxOptions value) {
        this.txOptions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the timeframe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeframe() {
        return timeframe;
    }

    /**
     * Sets the value of the timeframe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeframe(String value) {
        this.timeframe = value;
    }

    /**
     * Gets the value of the txLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxLine() {
        return txLine;
    }

    /**
     * Sets the value of the txLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxLine(String value) {
        this.txLine = value;
    }

}
